Exraction implementation with tika, Fast api endpoint integration, docker and compose infra addedImpleem
filetrust/cdr-content-integrity pull request #14
Opened 2021-05-29 19:35 UTC by gmuditdce

Implementation for #2  #3  #4 #5

2021-05-30 17:02 UTC, rajmbcoderx approved these changes
Looks good, I will help you next week to add unit tests and integration tests

2021-05-31 07:51 UTC, ggrig requested changes

2021-05-31 07:51 UTC, ggrig commented on cdr_content_extraction/api/routes/ExtractionResponse.py
> +
Although these are just stubs for several classes, we cannot put all those into a single file
Please create a separate file for each of the classes. 
The file name must be the same as the class name
For instance MetaDataResponse.py should contain the MetaDataResponse class definition

2021-05-31 07:51 UTC, ggrig commented on cdr_content_extraction/extraction-config.yml
> +      - application/java-vm
Why do we need all those content types?

2021-05-31 07:51 UTC, ggrig commented on cdr_content_extraction/extraction/ExtractionConfig.py
> +                config = yaml.safe_load(stream)
We use environment variables for configuration parameters
Please refer to how it is structured in https://github.com/filetrust/cdr-content-integrity/blob/main/cdr_content_management/common_settings/Config.py
Please utilize that file for handling config paramaters

2021-05-31 07:56 UTC, ggrig commented
The PR contains stubs for some classes.
This may be a good start point.
However, I am not sure if you should call those as an implementation of any of the tasks
It would make more sense if you could concentrate on a complete implementation of a single task per PR

2021-05-31 11:01 UTC, chrisdiao commented
@gmuditdce , could you please add version label.

2021-05-31 11:26 UTC, rajmbcoderx commented
@dinis-cruz-gw  (@gmuditdce @ggrig Merging this PR
We will have something that is working and extracting content to test.
We will see how we can incorporate some review comments @ggrig has on the PR in later PR, this one is getting big and should be a good starting point to build upon

2021-05-31 11:26 UTC, merged