Visual test runner with puppetter
filetrust/cdr-content-integrity pull request #36
Opened 2021-06-15 15:09 UTC by gmuditdce

Test runner used to run visual tests for #25

2021-06-16 04:52 UTC, ggrig commented on tests/runners/visual/script/upload.js
> +				if (fileExists) {
It might be a good idea to check the existence of both files before uploading any of them

2021-06-16 05:56 UTC, gmuditdce commented on tests/runners/visual/script/upload.js
> +				if (fileExists) {
@ggrig done

2021-06-23 11:03 UTC, chrisdiao commented
@ggrig @rajmbcoderx , could you please help us review this PR, please?

2021-06-23 11:51 UTC, ggrig requested changes

2021-06-23 11:51 UTC, ggrig commented on tests/runners/visual/script/upload.js
> +
The address should not be hardcoded like that
Please consider having it in a config or a .env file

2021-06-23 11:51 UTC, ggrig commented on tests/runners/visual/script/upload.js
> +			await delay(1000);
What's going to happen if delay(1000) turns not to be enough?
That case must be handled. I believe you need to either verify the expected action is completed or exit with a timeout error.
Also having the constants (1000, 5000, etc) hardcoded here will cause issues when you'd like to change those later. Please consider having named constants for these

2021-06-23 11:51 UTC, ggrig commented on tests/runners/visual/script/upload.js
> +				await delay(1000);
Same as above

2021-06-23 11:51 UTC, ggrig commented on tests/runners/visual/script/upload.js
> +                        await delay(5000);
Same as above

2021-06-24 07:04 UTC, gmuditdce commented on tests/runners/visual/script/upload.js
> +
ok

2021-06-24 07:06 UTC, gmuditdce commented on tests/runners/visual/script/upload.js
> +			await delay(1000);
will create named constants.
we are not waiting for the visualization to complete per file. it is asynchronous, the delay is to avoid cpu bursts when we have a large number of files. Moving them to a common place makes lot of sense.

2021-06-24 07:45 UTC, ggrig approved these changes

2021-06-26 11:20 UTC, gmuditdce commented
@GINAGC please merge this

2021-06-26 13:20 UTC, merged