Pdf conversion backend, frontend and fastapi integrated with content integrity
filetrust/cdr-content-integrity pull request #50
Opened 2021-06-20 16:28 UTC by gmuditdce

Implementation for #44 

Uploading Content Integrity PDF Convertor & Fastapi.mp4…

2021-06-21 02:41 UTC, rajmbcoderx approved these changes

2021-06-21 08:40 UTC, gmuditdce commented
@GINAGC @ChrisHolman @dinis-cruz-gw  I have removed the certificate directory from this PR
The certificates are self signed and should no cause any security risk as such.
There are needed for SSL (we generated these and signed them with a locally generated CA)
In case we cannot check these into git let me know i will change to http instead of using https

2021-06-21 08:46 UTC, gmuditdce commented
As confirmed by @ChrisHolman certs cannot go in git even if they are self signed.
I will update the code to use http instead of https.
Please hold the merge

2021-06-21 09:56 UTC, gmuditdce commented
@GINAGC @dinis-cruz-gw works with http now. removed certs and keys. May please be reviewed and merged

2021-06-23 11:03 UTC, chrisdiao commented
@ggrig @rajmbcoderx , could you please help us review this PR, please?

2021-06-23 11:35 UTC, ggrig requested changes

2021-06-23 11:35 UTC, ggrig commented on cdr-pdf-conversion/backend/express/src/pdf-engine/engine.js
> +        response.status(400).download('File too big or too small')
We better send the limits in the response.
For instance: "No file bigger than 1 MB is accepted"
That way the caller will know which files he can send 
Otherwise, they will need to guess and that is not a good user experience at all

2021-06-23 11:35 UTC, ggrig commented on cdr-pdf-conversion/backend/express/src/pdf-engine/engine.js
> +        return;
Same as above

2021-06-23 11:35 UTC, ggrig commented on cdr-pdf-conversion/backend/express/src/pdf-engine/engine.js
> +    if (fileBuffer.length < 4) {
Why don't we have MIN_FILE_SIZE for this?

2021-06-23 11:35 UTC, ggrig commented on cdr-pdf-conversion/frontend/server/src/utils/utils.js
> +        .toString(16)
No, we cannot have UUID generation like that
Please get it in a regular way with https://www.npmjs.com/package/uuid

2021-06-23 11:41 UTC, ggrig commented on README.md
> +
typo: deploymen -> deployment
"Only the value of REACT_APP_API_HOST may need to be changed - it depends on the deployment host"
sound clearer to me

2021-06-24 07:21 UTC, gmuditdce commented on cdr-pdf-conversion/backend/express/src/pdf-engine/engine.js
> +        response.status(400).download('File too big or too small')
ok

2021-06-24 07:22 UTC, gmuditdce commented on cdr-pdf-conversion/backend/express/src/pdf-engine/engine.js
> +        return;
ok

2021-06-24 07:23 UTC, gmuditdce commented on cdr-pdf-conversion/backend/express/src/pdf-engine/engine.js
> +    if (fileBuffer.length < 4) {
will add

2021-06-24 07:27 UTC, gmuditdce commented on cdr-pdf-conversion/frontend/server/src/utils/utils.js
> +        .toString(16)
will use https://www.npmjs.com/package/short-uuid (short required)

2021-06-25 09:01 UTC, ggrig approved these changes

2021-06-26 11:21 UTC, gmuditdce commented
@GINAGC please merge this

2021-06-26 13:21 UTC, merged